spring.application.name=ai-job-application-assistant
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
server.port=8080
server.error.include-message=always
server.error.include-binding-errors=always

spring.datasource.url=jdbc:postgresql://localhost:5432/ai_job_assistant
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# validate: valida que las entidades Java coincidan con las tablas creadas por Flyway sin alterarlas
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.locations=classpath:db/migration